export const COMMAND_QUEUE_NAME = "account-commands";

/**
 * Service class for enqueuing state engine directives into pg-boss.
 * Reuses the runtime-injected pg-boss connection thread pool.
 */
export class CommandQueue {
  /**
   * @param {Object} bossInstance - The active, bootstrapped pg-boss instance passed from the worker/processor
   */
  constructor(bossInstance) {
    if (!bossInstance) {
      throw new Error(
        "[CommandQueue Error] Cannot instantiate CommandQueue without an active pg-boss instance."
      );
    }
    this.boss = bossInstance;
  }

  /**
   * Pushes a resolved state-engine command into the pg-boss database engine.
   * @param {string} commandType - The target directive name (e.g., 'PROMOTE_PHASE', 'CREATE_PHASE2_ACCOUNT', 'SEND_LOGIN', 'MARK_FUNDED')
   * @param {Object} accountContext - The Mongoose account model snapshot containing baseline fields
   * @returns {Promise<string>} The unique tracking Job ID generated by pg-boss
   */
  async enqueueCommand(commandType, accountContext) {
    const jobPayload = {
      command: commandType,
      accountId: accountContext.accountId,
      timestamp: new Date(),
      metadata: {
        balance: accountContext.balance,
        equity: accountContext.equity,
        status: accountContext.status,
      },
    };

    const options = {
      retryLimit: 3,       // Automatically retry up to 3 times on downstream worker failures
      retryBackoff: true,  // Use exponential backoff spacing (e.g., 1s, 2s, 4s...)
      expireInMinutes: 30, // Execution timeout threshold for the consumer worker thread
    };

    try {
      // Keep at most one queued/retry/active copy of the same lifecycle
      // command per account. Periodic recovery can safely call this repeatedly.
      const singletonKey = `${accountContext.accountId}:${commandType}`;
      const jobId = typeof this.boss.sendOnce === "function"
        ? await this.boss.sendOnce(COMMAND_QUEUE_NAME, jobPayload, options, singletonKey)
        : await this.boss.send(
            COMMAND_QUEUE_NAME,
            jobPayload,
            { ...options, singletonKey },
          );

      if (jobId) {
        console.log(`[QUEUE] Enqueued ${commandType} for Account ${accountContext.accountId} | Job ID: ${jobId}`);
      } else {
        console.log(`[QUEUE] ${commandType} for Account ${accountContext.accountId} is already queued or active`);
      }
      return jobId;
    } catch (error) {
      console.error(`[QUEUE FAIL] Failed to push command ${commandType} to pg-boss:`, error);
      throw error; // Propagate error so the state manager can intercept/flag transaction degradation
    }
  } 
}
